### ISSUE TITLE
Rename second step of manual tests

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-milstd2525-plugin#6]
At the moment the second step has this text:

"Edit a value in the table using the code editor widget and check that it works correctly"

a user expect that after editing the symbology code in the table of attributes, the symbology is immeditaly applied,as the description seems to suggest.

I would then say that a text along the lines of

"Edit a value in the table using the code editor widget then in the next steps apply to the layer the MIL-STD-2525 symbology renderer and check that it works correctly"

will help understand better what to do.

**Comment by gioman** [comment]
@volaya @alexbruy sorry for this. I noticed now that at some point a step named

"Verify that the layer is rendered with MIL-STD-2525 symbology"

is presented to the user. But this shows *after* "Edit a value in the table using the code editor widget and check that it works correctly" and after the user is presented with the vector properties dialog open (that suggest to apply the MIL renderer) and after closing it.

After that after passing the "Verify that the layer is rendered with MIL-STD-2525 symbology" step the layer disappear, and if the user does not enter again in layer properties to apply MIL symbology the features do not show again, and the "Verify that the size of symbols has changed" cannot be checked.

**Comment by alexbruy** [comment]
@gioman there are two different tests here.

"Test code edit widget" used to verify SDIC code editor widget, in other words edit SIDC code with custom editor.

"Renderer test" used to check layer rendering, user only should apply renderer here and make sure it works.

In "Size change test" users should not enter any size value manually, this done automatically. User only should check that symbols size was changed.

**Comment by gioman** [comment]
@alexbruy yes I understand, The problem is that at some point the sequence does not become clear. Especially when the MIL renderer has been already applied but then features disappear, making necessary for the user to reapply then renderer to finish the steps (but this extra step is not part of tests).

**Comment by gioman** [comment]
@alexbruy I can make you a screencast.

**Comment by gioman** [comment]
Closing after some clarification with @alexbruy
